finishing ai conversation feature
gunmack/QuizLing pull request #38
Opened 2024-11-20 02:35 UTC by franollf

finished the ai conversation feature

2024-11-20 06:00 UTC, gunmack commented
Might want to make a component in `pages/api` to handle Gemini API interaction. Right now, the API key would be exposed to the browser due to having the `NEXT` keyword. Essentially just do the same thing you did for Text-to-speech

2024-11-20 06:02 UTC, gunmack requested changes

2024-11-20 06:02 UTC, gunmack commented on src/app/ai-conversations/page.js
Make a file in `pages/api` to handle API interaction
`NEXT_PUBLIC` would expose API key on the browser

2024-11-20 11:01 UTC, gunmack commented
Also I'm wondering why the workflow didn't run for this pr, did you fork the repo or clone it?

2024-11-20 22:28 UTC, franollf commented
no idea will fix it later

2024-11-21 06:40 UTC, gunmack approved these changes, later dismissed

2024-11-21 07:10 UTC, garrett-darts submitted a review, later dismissed

2024-11-21 07:18 UTC, garrett-darts approved these changes

2024-11-21 07:18 UTC, merged